{
 "title": "iptunnel 业务",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "客户端指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POP客户端软件版本号",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pop_version{ instance=\"44.222.141.176:6070\", job=\"iptunnel\", servicename=\"iptunnel\"}",
     "legendFormat": "{{exported_instance}}-{{version}}"
    }
   ]
  },
  {
   "title": "各用户机器发送流量速率（kbps）",
   "type": "timeseries",
   "description": "基于发送字节数的瞬时速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "pop_traffic_tx_rate{instance=\"44.222.141.176:6070\"} / 1000",
     "legendFormat": "{{exported_instance}}-{{user_machine_ip}}"
    }
   ]
  },
  {
   "title": "WireGuard peer连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pop_wireguard_peer_count{instance=\"44.222.141.176:6070\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "各带宽线路对端网络延迟（毫秒）",
   "type": "timeseries",
   "description": "通过ping测量的延迟，监控POP peer的延迟",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pop_wireguard_latency{instance=\"44.222.141.176:6070\"}",
     "legendFormat": "{{exported_instance}}-{{peer_ip}}"
    }
   ]
  },
  {
   "title": "各用户机器接收流量速率（kbps)",
   "type": "timeseries",
   "description": "基于接收字节数的瞬时速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "pop_traffic_rx_rate{instance=\"44.222.141.176:6070\"} / 1000",
     "legendFormat": "{{exported_instance}}-{{user_machine_ip}}"
    }
   ]
  },
  {
   "title": "与各peer节点连接状态",
   "type": "state-timeline",
   "description": "基于WireGuard握手状态",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "pop_wireguard_peer_status{instance=\"44.222.141.176:6070\"}",
     "legendFormat": "{{exported_instance}}-{{peer_ip}}"
    }
   ]
  },
  {
   "title": "POP客户端存活状态",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "pop_alive_status{instance=\"44.222.141.176:6070\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "域名解析服务状态",
   "type": "state-timeline",
   "description": "DNS服务健康检查",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "pop_dns_service_status{instance=\"44.222.141.176:6070\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "用户上传限速触发",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pop_rate_limit_hit{direction=\"upload\"}",
     "legendFormat": "{{exported_instance}}-{{user_machine_ip}}"
    }
   ]
  },
  {
   "title": "用户下载限速触发",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "pop_rate_limit_hit{direction=\"download\"}",
     "legendFormat": "{{exported_instance}}-{{user_machine_ip}}"
    }
   ]
  },
  {
   "title": "每个用户机器的发送字节数",
   "type": "stat",
   "description": "WireGuard peer发送的总字节数，user_machine_ip必须为用户内网IP",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pop_wireguard_tx_bytes{instance=\"44.222.141.176:6070\"}",
     "legendFormat": "{{exported_instance}}-{{user_machine_ip}}"
    }
   ]
  },
  {
   "title": "每个用户机器的接收字节数",
   "type": "stat",
   "description": "WireGuard peer接收的总字节数，user_machine_ip必须为用户内网IP",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pop_wireguard_rx_bytes{instance=\"44.222.141.176:6070\"}",
     "legendFormat": "{{exported_instance}}-{{user_machine_ip}}"
    }
   ]
  },
  { "title": "服务端指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "服务端软件版本号",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_version{ instance=\"44.222.141.176:6070\", job=\"iptunnel\", servicename=\"iptunnel\"}",
     "legendFormat": "{{servicename}} {{version}}"
    }
   ]
  },
  {
   "title": "服务端健康状态",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 33 },
   "targets": [
    {
     "expr": "server_health_check{ instance=\"44.222.141.176:6070\", job=\"iptunnel\", servicename=\"iptunnel\"}",
     "legendFormat": "服务端健康检查状态"
    },
    {
     "expr": "server_db_status{ instance=\"44.222.141.176:6070\", job=\"iptunnel\", servicename=\"iptunnel\"}",
     "legendFormat": "数据库状态"
    }
   ]
  },
  {
   "title": "各用户订单个数",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT user_code, COUNT(*)  FROM orders WHERE deleted_at IS NULL GROUP BY user_code"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"POP机个数\" FROM machines WHERE type='pop' AND deleted_at IS NULL"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"已分配内网数\" FROM intra_ips WHERE allocated=1 AND deleted_at IS NULL"
    },
    {
     "rawSql": "SELECT COUNT(*) as \"用户总数\" FROM users WHERE deleted_at IS NULL"
    },
    {
     "rawSql": "SELECT COUNT(DISTINCT user_code) as \"活跃用户数\" FROM orders WHERE deleted_at IS NULL"
    }
   ]
  },
  {
   "title": "服务端到POP延迟（毫秒）",
   "type": "timeseries",
   "description": "从服务端ping POP公网IP测量的延迟",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "server_pop_latency{instance=\"44.222.141.176:6070\", job=\"iptunnel\"}",
     "legendFormat": "{{pop_intra_ip}} ({{pop_ip}})"
    }
   ]
  },
  {
   "title": "POP端与服务端通信状态",
   "type": "state-timeline",
   "description": "定期心跳检查",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "server_pop_communication_status{instance=\"44.222.141.176:6070\"}",
     "legendFormat": "{{pop_id}}"
    }
   ]
  },
  {
   "title": "各线路带宽总量（Mbps）",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "dataset": "iptunnel",
     "rawSql": "SELECT bandwidth_line_code, total_bandwidth FROM bandwidth_lines WHERE is_active=1 AND deleted_at IS NULL"
    },
    {
     "dataset": "iptunnel",
     "rawSql": "SELECT bandwidth_line_code, user_code, SUM(bandwidth) FROM configs WHERE status='active' AND deleted_at IS NULL GROUP BY bandwidth_line_code, user_code"
    }
   ]
  },
  {
   "title": "各线路带宽被购买使用情况（Mbps）",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "dataset": "iptunnel",
     "rawSql": "SELECT bandwidth_line_code, user_code, SUM(bandwidth) AS total_purchase FROM configs WHERE status='active' AND deleted_at IS NULL GROUP BY bandwidth_line_code, user_code"
    }
   ]
  }
 ]
}