{
 "title": "IPTunnel 服务端监控",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values({servicename=~\"iptunnel\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "业务统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "服务端软件版本号",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_version", "legendFormat": "{{instance}} ~ {{version}}" }
   ]
  },
  {
   "title": "服务端健康状态",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "targets": [
    { "expr": "server_health_check", "legendFormat": "服务端健康检查状态" },
    { "expr": "server_db_status", "legendFormat": "数据库状态" }
   ]
  },
  {
   "title": "各用户订单个数",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT user_code, COUNT(*)  FROM orders WHERE deleted_at IS NULL GROUP BY user_code"
    }
   ]
  },
  {
   "title": "服务端到POP延迟（毫秒）",
   "type": "timeseries",
   "description": "从服务端ping POP公网IP测量的延迟",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "server_pop_latency{instance=~\"$instance\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "POP端与服务端通信状态",
   "type": "state-timeline",
   "description": "定期心跳检查",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "server_pop_communication_status{instance=~\"$instance\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}